---
name: MooseX-Role-Strict
version: 0.03
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: use strict 'roles'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Most: 0.21
requires:
  Moose: 0.75
configure_requires:
  Module::Build: 0.35
provides:
  MooseX::Meta::Role::Strict:
    file: lib/MooseX/Meta/Role/Strict.pm
    version: 0.02
  MooseX::Role::Strict:
    file: lib/MooseX/Role/Strict.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
